Repository oauthjs/node-oauth2-server, pull requests merged in 2018-08, with the labels that each got.

#472 Breaking Change: Set server_error Code to 500
  lib/errors/server-error.js
  test/integration/handlers/token-handler_test.js
Labels: awaiting-response

#289 #288 Revoke handler
  lib/handlers/revoke-handler.js
  lib/server.js
  test/integration/handlers/revoke-handler_test.js
  test/integration/server_test.js
  test/unit/handlers/revoke-handler_test.js
  test/unit/server_test.js
Labels: awaiting-response, enhancement, v3

#501 fix; correct client ID check in refresh_token grant type
  lib/grant-types/refresh-token-grant-type.js
  test/integration/grant-types/refresh-token-grant-type_test.js
Labels: awaiting-response, bug
